### ISSUE TITLE
Can anybody help add the I2I function with text text describe.

### ISSUE THREAD

**Issue by Alfred-Duncan** [kakaobrain/karlo#10]
I noticed that in i2i.py, the function can receive prompt, but in the gradio ui, there only picture token.
I tried to add the args for that, but I didn't good at gradio website and failed, maybe anybody can help that?

And batch_size not a good option to choose, only one batch size need lots of memories of CUDA even 23GB at NVIDIA 3090.
If there can be a batch count option, the model canbe perfect......

**Comment by saehoonkim** [comment]
Hi @Alfred-Duncan , thanks for your interests to this project. In our image variation example, we've found that the text information was ignored to variate the input image. We think that this behavior happens since the signal of clip image feature is stronger than that of text feature in classifier-free guidance. 

And, in your case, you can try HF's diffusers library, to which karlo has been recently integrated. In diffusers, the checkpoints has been stored in fp16 rather than fp32, improving latency and memory requirments.
